--create table album (
--      id varchar(30) NOT NULL,
--      title varchar(30) NOT NULL,
--      artist varchar(30) NULL,
--      producer varchar(30) NULL,
--      recordLabel varchar(30) NULL,
--      releaseYear int(30) NULL,
--      copiesSold int(30) NULL,
--      CONSTRAINT album_pk PRIMARY KEY (id)
--  );